# Generated by Django 6.0.7 on 2026-08-19 21:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items_snapshot',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
