# Generated by Django 6.0.7 on 2026-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(choices=[('اولیه', 'اولیه'), ('بازیافتی', 'بازیافتی')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_urls', models.JSONField(default=list)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_stock', models.IntegerField(blank=True, null=True)),
                ('new_stock', models.IntegerField()),
                ('reason', models.CharField(choices=[('initial', 'اولیه'), ('sale', 'فروش'), ('restock', 'تامین مجدد'), ('adjustment', 'تعدیل')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
