# Generated by Django 6.0.7 on 2026-07-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_histories', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_histories', to='products.product'),
        ),
    ]
