# Generated by Django 6.0.7 on 2026-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_pricehistory_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='تگ پرفروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اطلاعات بسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربرد / زیردسته'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد شمارش'),
        ),
    ]
