# Generated by Django 6.0.7 on 2026-09-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
